# Generated by Django 5.1.7 on 2025-03-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('academic', 'Academic Project'), ('client', 'Client Project'), ('personal', 'Personal Project')], default='personal', max_length=20),
        ),
    ]
