# Generated by Django 5.1.7 on 2025-03-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_project_link_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
