# Generated by Django 5.1.7 on 2025-03-17 20:19

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_project_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='description'),
        ),
    ]
